// tslint:disable
/**
 * Monitor-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MonitorUser
 */
export interface MonitorUser {
  /**
   *
   * @type {number}
   * @memberof MonitorUser
   */
  userId?: number;
  /**
   *
   * @type {string}
   * @memberof MonitorUser
   */
  username?: string;
  /**
   *
   * @type {string}
   * @memberof MonitorUser
   */
  account?: string;
  /**
   *
   * @type {string}
   * @memberof MonitorUser
   */
  password?: string;
  /**
   *
   * @type {string}
   * @memberof MonitorUser
   */
  createdAt?: string;
  /**
   *
   * @type {string}
   * @memberof MonitorUser
   */
  updatedAt?: string;
  /**
   *
   * @type {number}
   * @memberof MonitorUser
   */
  createdBy?: number;
  /**
   *
   * @type {number}
   * @memberof MonitorUser
   */
  updatedBy?: number;
}
