// tslint:disable
/**
 * Monitor-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MonitorRole
 */
export interface MonitorRole {
  /**
   *
   * @type {number}
   * @memberof MonitorRole
   */
  roleId?: number;
  /**
   *
   * @type {string}
   * @memberof MonitorRole
   */
  roleKey?: string;
  /**
   *
   * @type {string}
   * @memberof MonitorRole
   */
  remark?: string;
  /**
   *
   * @type {string}
   * @memberof MonitorRole
   */
  createdAt?: string;
  /**
   *
   * @type {string}
   * @memberof MonitorRole
   */
  updatedAt?: string;
  /**
   *
   * @type {number}
   * @memberof MonitorRole
   */
  createdBy?: number;
  /**
   *
   * @type {number}
   * @memberof MonitorRole
   */
  updatedBy?: number;
}
