// tslint:disable
/**
 * Monitor-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MonitorAlarmRule
 */
export interface MonitorAlarmRule {
  /**
   *
   * @type {number}
   * @memberof MonitorAlarmRule
   */
  ruleId?: number;
  /**
   *
   * @type {number}
   * @memberof MonitorAlarmRule
   */
  ruleType?: number;
  /**
   *
   * @type {number}
   * @memberof MonitorAlarmRule
   */
  threshold?: number;
  /**
   *
   * @type {string}
   * @memberof MonitorAlarmRule
   */
  createdAt?: string;
  /**
   *
   * @type {string}
   * @memberof MonitorAlarmRule
   */
  updatedAt?: string;
  /**
   *
   * @type {number}
   * @memberof MonitorAlarmRule
   */
  createdBy?: number;
  /**
   *
   * @type {number}
   * @memberof MonitorAlarmRule
   */
  updatedBy?: number;
}
