// tslint:disable
/**
 * Monitor-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MonitorExam
 */
export interface MonitorExam {
  /**
   *
   * @type {number}
   * @memberof MonitorExam
   */
  examId?: number;
  /**
   *
   * @type {string}
   * @memberof MonitorExam
   */
  startTime?: string;
  /**
   *
   * @type {string}
   * @memberof MonitorExam
   */
  endTime?: string;
  /**
   *
   * @type {string}
   * @memberof MonitorExam
   */
  remark?: string;
  /**
   *
   * @type {string}
   * @memberof MonitorExam
   */
  createdAt?: string;
  /**
   *
   * @type {string}
   * @memberof MonitorExam
   */
  updatedAt?: string;
  /**
   *
   * @type {number}
   * @memberof MonitorExam
   */
  createdBy?: number;
  /**
   *
   * @type {number}
   * @memberof MonitorExam
   */
  updatedBy?: number;
}
