// tslint:disable
/**
 * Monitor-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MonitorUserRole
 */
export interface MonitorUserRole {
    /**
     * 
     * @type {number}
     * @memberof MonitorUserRole
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof MonitorUserRole
     */
    roleId?: number;
    /**
     * 
     * @type {string}
     * @memberof MonitorUserRole
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof MonitorUserRole
     */
    updatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof MonitorUserRole
     */
    createdBy?: number;
    /**
     * 
     * @type {number}
     * @memberof MonitorUserRole
     */
    updatedBy?: number;
}


