// tslint:disable
/**
 * Monitor-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MonitorFileInfo
 */
export interface MonitorFileInfo {
    /**
     * 
     * @type {number}
     * @memberof MonitorFileInfo
     */
    fileId?: number;
    /**
     * 
     * @type {string}
     * @memberof MonitorFileInfo
     */
    fileName?: string;
    /**
     * 
     * @type {string}
     * @memberof MonitorFileInfo
     */
    fileKey?: string;
    /**
     * 
     * @type {string}
     * @memberof MonitorFileInfo
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof MonitorFileInfo
     */
    updatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof MonitorFileInfo
     */
    createdBy?: number;
    /**
     * 
     * @type {number}
     * @memberof MonitorFileInfo
     */
    updatedBy?: number;
}


