// tslint:disable
/**
 * Monitor-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MonitorExam } from './monitor-exam';

/**
 * 
 * @export
 * @interface PageMonitorExam
 */
export interface PageMonitorExam {
    /**
     * 
     * @type {Array<MonitorExam>}
     * @memberof PageMonitorExam
     */
    records?: Array<MonitorExam>;
    /**
     * 
     * @type {number}
     * @memberof PageMonitorExam
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof PageMonitorExam
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PageMonitorExam
     */
    maxPageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PageMonitorExam
     */
    totalPage?: number;
    /**
     * 
     * @type {number}
     * @memberof PageMonitorExam
     */
    totalRow?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageMonitorExam
     */
    optimizeCountQuery?: boolean;
}


