// tslint:disable
/**
 * Monitor-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MonitorUser } from './monitor-user';

/**
 * 
 * @export
 * @interface TableDataInfoMonitorUser
 */
export interface TableDataInfoMonitorUser {
    /**
     * 总记录数
     * @type {number}
     * @memberof TableDataInfoMonitorUser
     */
    total?: number;
    /**
     * 列表数据
     * @type {Array<MonitorUser>}
     * @memberof TableDataInfoMonitorUser
     */
    rows?: Array<MonitorUser>;
    /**
     * 页数
     * @type {number}
     * @memberof TableDataInfoMonitorUser
     */
    pages?: number;
    /**
     * 
     * @type {number}
     * @memberof TableDataInfoMonitorUser
     */
    code?: number;
}


